export enum EVENTS {
    REDO_TEST,
    OPENAI_BASE_REQUEST_ERROR,
    OPENAI_RANKING_REQUEST_ERROR,
    OPENAI_TAGS_REQUEST_ERROR,
    RANKING_REQUEST_FAILED_AFTER_ATTEMPTS,
    LOCAL_STORAGE_RESULT_ERROR,
    EMAIL_SUBSCRIPTION_ERROR,
}
